steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/meridian-prime/platform-core:minimal', '-f', 'Dockerfile.minimal', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/meridian-prime/platform-core:minimal']