# Application Alert Rules for EnterpriseLand

groups:
  - name: application_alerts
    interval: 30s
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total[5m]))
          ) > 0.05
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"
          runbook_url: "https://docs.enterpriseland.com/runbooks/high-error-rate"

      # Slow Response Time
      - alert: SlowResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
          ) > 1.0
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "95th percentile response time is high"
          description: "95th percentile response time is {{ $value }}s"
          runbook_url: "https://docs.enterpriseland.com/runbooks/slow-response"

      # Low Cache Hit Rate
      - alert: LowCacheHitRate
        expr: cache_hit_rate_percent < 80
        for: 15m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Cache hit rate is low"
          description: "Cache hit rate is {{ $value }}%"
          runbook_url: "https://docs.enterpriseland.com/runbooks/low-cache-hit"

      # API Endpoint Down
      - alert: APIEndpointDown
        expr: up{job="blackbox", instance=~".*api.*"} == 0
        for: 2m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "API endpoint is down"
          description: "API endpoint {{ $labels.instance }} is not responding"
          runbook_url: "https://docs.enterpriseland.com/runbooks/api-down"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}%"
          runbook_url: "https://docs.enterpriseland.com/runbooks/high-memory"

      # Database Connection Pool Exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: db_connections_active / db_connections_max > 0.9
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of database connections are in use"
          runbook_url: "https://docs.enterpriseland.com/runbooks/db-connections"

      # Slow Database Queries
      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.95,
            sum(rate(db_query_duration_seconds_bucket[5m])) by (le)
          ) > 0.5
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Database queries are slow"
          description: "95th percentile query time is {{ $value }}s"
          runbook_url: "https://docs.enterpriseland.com/runbooks/slow-queries"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: system_disk_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Disk usage is high"
          description: "Disk usage is {{ $value }}%"
          runbook_url: "https://docs.enterpriseland.com/runbooks/high-disk"

      # Service Unhealthy
      - alert: ServiceUnhealthy
        expr: system_health_status < 3
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Service health check failing"
          description: "Service health status is {{ $value }} (1=critical, 2=unhealthy, 3=degraded, 4=healthy)"
          runbook_url: "https://docs.enterpriseland.com/runbooks/service-health"

      # Celery Queue Backlog
      - alert: CeleryQueueBacklog
        expr: celery_queue_length > 1000
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Celery queue has large backlog"
          description: "Celery queue has {{ $value }} pending tasks"
          runbook_url: "https://docs.enterpriseland.com/runbooks/celery-backlog"