# Blackbox Exporter Configuration

modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204]
      method: GET
      headers:
        Accept: "application/json"
      fail_if_not_ssl: false
      fail_if_body_not_matches_regexp: []
      tls_config:
        insecure_skip_verify: true

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204]
      method: POST
      headers:
        Content-Type: "application/json"
      body: '{}'

  tcp_connect:
    prober: tcp
    timeout: 5s

  dns_check:
    prober: dns
    timeout: 5s
    dns:
      query_name: "www.example.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"