name: Release Platform Core

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: gcr.io
  PROJECT_ID: meridian-prime
  SERVICE_NAME: platform-core
  REGION: us-central1

jobs:
  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and Push
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }} .
        docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest .
        docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
        docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
        region: ${{ env.REGION }}
        env_vars: |
          DJANGO_SETTINGS_MODULE=platform_core.settings.production
          CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
        secrets: |
          DATABASE_URL=database-url:latest
          REDIS_URL=redis-url:latest
          SECRET_KEY=django-secret-key:latest
          JWT_SECRET_KEY=jwt-secret-key:latest
          AWS_ACCESS_KEY_ID=aws-access-key:latest
          AWS_SECRET_ACCESS_KEY=aws-secret-key:latest

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: deploy
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Platform Core ${{ github.ref_name }}
        body: |
          ## Platform Core Release ${{ github.ref_name }}
          
          ### What's Changed
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          
          ### Docker Image
          ```
          ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
          ```
        draft: false
        prerelease: false